export const MERCHANTS = [
  {
    id: 'mch_d2c_01',
    name: 'TechGear India',
    category: 'D2C E-Commerce',
    badgeColor: 'blue',
    description: 'High-volume electronics & accessories retailer',
    defaultChannel: 'WhatsApp Nudge'
  },
  {
    id: 'mch_saas_02',
    name: 'SaaSify Cloud',
    category: 'SaaS Subscriptions',
    badgeColor: 'purple',
    description: 'B2B & B2C SaaS platform with recurring UPI Autopay',
    defaultChannel: 'Mandate Retry Sequencer'
  },
  {
    id: 'mch_b2b_03',
    name: 'Nexus Logistics',
    category: 'B2B Enterprise Invoices',
    badgeColor: 'amber',
    description: 'Supply chain & logistics vendor operating on Net-30 invoice terms',
    defaultChannel: 'Promise-to-Pay Chaser'
  }
];

export const INITIAL_TRANSACTIONS = [
  // --- D2C E-Commerce Merchant (TechGear India) ---
  {
    id: 'TXN-D2C-1001',
    merchantId: 'mch_d2c_01',
    merchantName: 'TechGear India',
    category: 'D2C E-Commerce',
    customerName: 'Kavin',
    customerEmail: 'kavin@example.com',
    customerPhone: '+91 98765 43210',
    amount: 4999,
    itemDescription: 'Noise-Cancelling Wireless Headphones',
    failureReason: 'BAD_REQUEST_PAYMENT_TIMED_OUT',
    failureDetail: 'HDFC NetBanking gateway timed out at 3D-Secure verification page',
    timestamp: '2026-09-04 11:20:15',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },
  {
    id: 'TXN-D2C-1002',
    merchantId: 'mch_d2c_01',
    merchantName: 'TechGear India',
    category: 'D2C E-Commerce',
    customerName: 'Ananya Verma',
    customerEmail: 'ananya.v@example.com',
    customerPhone: '+91 98123 45678',
    amount: 8999,
    itemDescription: 'Smart Fitness Watch Series 5',
    failureReason: 'USER_ABANDONED_PRICE_HESITATION',
    failureDetail: 'Customer hovered on payment screen for 3 minutes before closing tab',
    timestamp: '2026-09-04 11:45:00',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },
  {
    id: 'TXN-D2C-1003',
    merchantId: 'mch_d2c_01',
    merchantName: 'TechGear India',
    category: 'D2C E-Commerce',
    customerName: 'Vikram Patel',
    customerEmail: 'vikram.p@example.com',
    customerPhone: '+91 97654 32109',
    amount: 3499,
    itemDescription: 'RGB Mechanical Gaming Keyboard',
    failureReason: 'GATEWAY_ERROR_UPI_SERVER_DOWN',
    failureDetail: 'SBI UPI server temporarily unresponsive during intent invocation',
    timestamp: '2026-09-04 12:05:30',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },

  // --- SaaS Subscriptions Merchant (SaaSify Cloud) ---
  {
    id: 'TXN-SAAS-2001',
    merchantId: 'mch_saas_02',
    merchantName: 'SaaSify Cloud',
    category: 'SaaS Subscriptions',
    customerName: 'Priya Sundaram',
    customerEmail: 'priya@techstartup.io',
    customerPhone: '+91 99887 76655',
    amount: 2499,
    itemDescription: 'Pro Developer Plan (Monthly Autopay)',
    failureReason: 'INSUFFICIENT_FUNDS_TEMPORARY',
    failureDetail: 'UPI Autopay mandate debit failed: Insufficient balance prior to salary credit',
    timestamp: '2026-09-04 09:15:00',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },
  {
    id: 'TXN-SAAS-2002',
    merchantId: 'mch_saas_02',
    merchantName: 'SaaSify Cloud',
    category: 'SaaS Subscriptions',
    customerName: 'Karan Malhotra',
    customerEmail: 'karan.m@agencygrowth.com',
    customerPhone: '+91 98711 22334',
    amount: 14999,
    itemDescription: 'Business Growth Suite (Annual SI)',
    failureReason: 'EXPIRED_CREDIT_CARD',
    failureDetail: 'Standing Instruction debit rejected: Card expired on 08/26',
    timestamp: '2026-09-04 10:30:45',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },
  {
    id: 'TXN-SAAS-2003',
    merchantId: 'mch_saas_02',
    merchantName: 'SaaSify Cloud',
    category: 'SaaS Subscriptions',
    customerName: 'Sneha Kapoor',
    customerEmail: 'sneha@designstudio.in',
    customerPhone: '+91 96543 21876',
    amount: 1299,
    itemDescription: 'AI Analytics Add-on (Monthly Autopay)',
    failureReason: 'MANDATE_EXECUTION_LIMIT_EXCEEDED',
    failureDetail: 'Bank rejected mandate: Daily debit velocity limit reached for account',
    timestamp: '2026-09-04 12:10:00',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },

  // --- B2B Enterprise Merchant (Nexus Logistics) ---
  {
    id: 'TXN-B2B-3001',
    merchantId: 'mch_b2b_03',
    merchantName: 'Nexus Logistics',
    category: 'B2B Enterprise Invoices',
    customerName: 'Apex Retail Solutions Pvt Ltd',
    customerEmail: 'finance@apexretail.co.in',
    customerPhone: '+91 98111 00998',
    amount: 125000,
    itemDescription: 'Q3 Interstate Freight Shipping & Warehousing Invoice #NX-8821',
    failureReason: 'OVERDUE_INVOICE_NET30_EXCEEDED',
    failureDetail: 'Invoice past 18 days due date. Previous reminder unopened.',
    timestamp: '2026-09-01 08:00:00',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  },
  {
    id: 'TXN-B2B-3002',
    merchantId: 'mch_b2b_03',
    merchantName: 'Nexus Logistics',
    category: 'B2B Enterprise Invoices',
    customerName: 'BlueSky Exports',
    customerEmail: 'accounts@blueskyexports.com',
    customerPhone: '+91 97123 98765',
    amount: 78000,
    itemDescription: 'Customs Clearance & Cold Chain Transport Invoice #NX-8904',
    failureReason: 'OVERDUE_INVOICE_APPROVAL_PENDING',
    failureDetail: 'Client accounts team requested vendor PO reconciliation prior to payout',
    timestamp: '2026-09-02 09:30:00',
    status: 'AT_RISK',
    attemptsCount: 0,
    maxAttemptsAllowed: 3,
    optOut: false,
    history: []
  }
];
